---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webserver
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
  - port: 80
    targetPort: 80
    nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-webserver
  labels:
    app.kubernetes.io/name: webserver

  annotations:
    fluxcd.io/tag.webserver: glob:1.0.*
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
    spec:
      containers:
      - name: webserver
        image: syednadeembe/html-server-image:v3
        ports:
        - containerPort: 80
