apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app.kubernetes.io/name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
    spec:
      containers:
      - name: webserver-2
        image: html-server-image:v1
        ports:
        - containerPort: 80
