---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webserver
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  anotations:
    fluxcd.io/tag.webserver: html-server-image:v*
    fluxcd.io/automated: "true"
  labels:
    app.kubernetes.io/name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
    spec:
      containers:
      - name: webserver
        image: html-server-image:v1
        ports:
        - containerPort: 80
