apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: webserver
  name: webserver
spec:
  containers:
  - image: html-server-image:v1
    name: webserver
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
